export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";
//
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAIL = "SIGN_UP_FAIL";
export const SHOW_PROFILE = "SHOW_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
//
export const TELEPORT_QUESTION_ANSWERS = "TELEPORT_QUESTION_ANSWERS";
export const IMPORT_QUESTION_ANSWERS = "IMPORT_QUESTION_ANSWERS";
export const CREATE_QUESTION_ANSWERS = "CREATE_QUESTION_ANSWERS";
export const UPDATE_QUESTION_ANSWERS = "UPDATE_QUESTION_ANSWERS";
export const UPDATE_TIME = "UPDATE_TIME";

export const SHOW_QUESTION_ANSWERS = "SHOW_QUESTION_ANSWERS";
export const SHOW_QUESTION_AFTER_DELETE = "SHOW_QUESTION_AFTER_DELETE";
export const SHOW_SUBJECT = "SHOW_SUBJECT";
export const GET_QUESTION_TABLE_BY_SUBJECT = "GET_QUESTION_TABLE_BY_SUBJECT";
export const SHOW_QUESTION_TABLE_BY_SUBJECT = "SHOW_QUESTION_TABLE_BY_SUBJECT";

export const CREATE_QUESTION_TABLE = "CREATE_QUESTION_TABLE";
export const UPDATE_QUESTION_TABLE_QUESTION = "UPDATE_QUESTION_TABLE_QUESTION";
export const UPDATE_QUESTION_TABLE = "UPDATE_QUESTION_TABLE";

export const SHOW_ANSWER_RECORD = "SHOW_ANSWER_RECORD";

//USER
export const GET_REPORT = "GET_REPORT";
export const SHOW_QUESTION_TABLE = "SHOW_QUESTION_TABLE";
export const SHOW_QUESTION_TABLE_COMPLETED = "SHOW_QUESTION_TABLE_COMPLETED";
export const GET_QUESTION_TABLE_COMPLETED = "GET_QUESTION_TABLE_COMPLETED";
export const UPDATE_USER = "UPDATE_USER";
export const CLOSE_CODE_QUESTION_TABLE = "CLOSE_CODE_QUESTION_TABLE";
export const SHOW_ONE_QUESTION_TABLE = "SHOW_ONE_QUESTION_TABLE";
export const SHOW_USER_ATTEMPT = "SHOW_USER_ATTEMPT";
export const CHECK_USER_DO_QUIZ = "CHECK_USER_DO_QUIZ";
//campaign
export const CREATE_CAMPAIGN = "CREATE_CAMPAIGN";
export const SHOW_CAMPAIGNS = "SHOW_CAMPAIGNS";
export const SHOW_CAMPAIGN = "SHOW_CAMPAIGN";
export const GET_CAMPAIGNS = "GET_CAMPAIGNS";

//GROUP_CANDIDATES
export const SHOW_AVAILABLE_CANDIDATES = "SHOW_AVAILABLE_CANDIDATES";
export const SHOW_INTERVIEW_CANDIDATES = "SHOW_INTERVIEW_CANDIDATES";
export const INSERT_INTERVIEW_CANDIDATES = "INSERT_INTERVIEW_CANDIDATES";
export const INSERT_AVAILABLE_CANDIDATES = "INSERT_AVAILABLE_CANDIDATES";
export const DELETE_AVAILABLE_CANDIDATES = "DELETE_AVAILABLE_CANDIDATES";
export const DELETE_INTERVIEW_CANDIDATES = "DELETE_INTERVIEW_CANDIDATES";
export const UPDATE_INTERVIEW_CANDIDATES = "UPDATE_INTERVIEW_CANDIDATES";

export const SEND_CV_SUCCESS = "SEND_CV_SUCCESS";
// candidate
export const CANDIDATE_SENT_CV = "CANDIDATE_SENT_CV";
export const CANDIDATE_NOT_SEND_CV = "CANDIDATE_NOT_SEND_CV";

// access to push
export const ACCESS_TO_PUSH = "ACCESS_TO_PUSH";
export const ACCESS_TO_PUSH_QUIZ = "ACCESS_TO_PUSH_QUIZ";
//interview
export const CREATE_INTERVIEW = "CREATE_INTERVIEW";
export const SHOW_INTERVIEWS = "SHOW_INTERVIEWS";
export const GET_INTERVIEWS = "GET_INTERVIEWS";
export const GET_COMPLETED_INTERVIEWS = "GET_COMPLETED_INTERVIEWS";
export const GET_COMPLETED_INTERVIEWS_API = "GET_COMPLETED_INTERVIEWS_API";

///
export const SHOW_WORK_TYPE = "SHOW_WORK_TYPE";
export const SHOW_LEVEL = "SHOW_LEVEL";
